### PR TITLE
fix: Typing Effect is Breaking the Word Wrap 

### PR DESCRIPTION
**Pull request by DonaldReddy**
## Issue number 

fixes: #223 

## Video/Screenshots (mandatory)

image

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Comment by DonaldReddy** [comment]
@surajvast1 please look into this pr

**Comment by surajvast1** [comment]
LGTM 🎉 @PranavBarthwal Approve this

**Comment by PranavBarthwal** [comment]
@DonaldReddy Merge conflicts need to be resolved!

**Comment by DonaldReddy** [comment]
Will do @PranavBarthwal

**Comment by PranavBarthwal** [comment]
Also can you fix the typing effect string, I'll update the difficulty level for this. Its showing Xodeyysey. Change it to synonyms starting with X like Xcurcsion, Xploration.

**Comment by DonaldReddy** [comment]
will do @PranavBarthwal

**Comment by DonaldReddy** [comment]
@PranavBarthwal please review this PR

**Review by PranavBarthwal — APPROVED** [review]
good work :)

**Pull request merged**
