### PR TITLE
Add buttons for all pages in navbar

### LINKED ISSUE #196: Add buttons for all pages in navbar
### Describe your issue

Add buttons in navbar for all pages inside the `pages` folder

### Steps to reproduce the bug

check navbar

### What was the expected result?

The navbar should have buttons for all pages

### Put here any screenshots or videos (optional)

image

### Would you like to work on this issue?

No

### How will you fix this? (Only if you want to work on this issue)

Add buttons named `EPIC` for earthPic page
and `NeoWs` for asteroid-info page

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #196

# Title of Issue and Pull Request must be Same

## Issue number 

Fixes #196

## Video/Screenshots (mandatory)

image

After Chnages:

https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/862fa388-8315-4394-b776-b792e05c2705

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:
Code Changes:
```
<li class="nav-item " id="new">
          <a class="nav-link text-light decorate-text" href="./Pages/asteroid-info/index.html">NeoWs</a>
      </li>
      <li class="nav-item " id="epic">
          <a class="nav-link text-light decorate-text" href="./Pages/earthPics/index.html">EPIC View</a>
        </li>
```

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
I guess you forgeot to save the changes before pushing :)

image

**Comment by Anjaliavv51** [comment]
I did , once check in code in nav bar section.

**Comment by PranavBarthwal** [comment]
> I did , once check in code in nav bar section.

The code you pushed is showing just a new line in index.html file. see the screenshot

image

**Comment by Anjaliavv51** [comment]
image

Now it's done!

**Comment by PranavBarthwal** [comment]
> image
> 
> Now it's done!

yeah, now its fixed.

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
