### PR TITLE
martian rover imagery page

### PR DESCRIPTION
**Pull request by Chandu6702**
closes: #225 

## Video/Screenshots (mandatory)

https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/77005df1-add3-48d9-819c-2a6c90551919

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Comment by Chandu6702** [comment]
hey @surajvast1, I created a page for Mars rover images as you requested. please review and merge this.

**Comment by surajvast1** [comment]
Looks fine @PranavBarthwal

**Review by PranavBarthwal — APPROVED** [review]

**Comment by Chandu6702** [comment]
@surajvast1 and @PranavBarthwal  please add gssoc label for the PR

**Comment by Chandu6702** [comment]
@PranavBarthwal please add the gssoc label

**Pull request merged**
