### PR TITLE
Add Chatbot

### PR DESCRIPTION
**Pull request by chocolatecupcake2002**
# Add Chatbot

## Screenshots

image

image

image

image

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:

1. The chatbot files are kept under the components directory.
2. Limited set of Banned words are listed to prevent unrequired searches by users.
3. For dynamics of vite, the flask file is migrated to a jsx file as rendering templates using jinja engine throws error for front-end server.
4. Queries and Api are under limited set of queries per month under the free-use tier for google custom search.

### CODE REVIEW

**Comment by chocolatecupcake2002** [comment]
@PranavBarthwal The security check is raised for API..  should I remove the key and custom search engine ID?

Any suggestions will be great! thanks

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal The security check is raised for API..  should I remove the key and custom search engine ID?
> 
> Any suggestions will be great! thanks

Add it as an environment variable. 
Also add it in the demo .env file

**Comment by chocolatecupcake2002** [comment]
> > @PranavBarthwal The security check is raised for API..  should I remove the key and custom search engine ID?
> > Any suggestions will be great! thanks
> 
> Add it as an environment variable. Also add it in the demo .env file

i will leave it as DEMO_KEY in demo .env file?

**Comment by PranavBarthwal** [comment]
> > > @PranavBarthwal The security check is raised for API..  should I remove the key and custom search engine ID?
> > > Any suggestions will be great! thanks
> > 
> > Add it as an environment variable. Also add it in the demo .env 
> 
> i will leave it as DEMO_KEY in demo .env file? for the environment variable

Yeaah, just name it properly like CHATBOT_API_KEY & CUSTOM_SEARCH_ENGINE_ID

**Comment by chocolatecupcake2002** [comment]
@PranavBarthwal 
I have changed the values in files, yet same issue is present.. is it cached or i try a commit after sometime?

**Comment by chocolatecupcake2002** [comment]
> @PranavBarthwal I have changed the values in files, yet same issue is present.. is it cached or i try a commit after sometime?
> 
> image
> 
> Screenshot 2024-06-05 165207

@PranavBarthwal

**Comment by chocolatecupcake2002** [comment]
@PranavBarthwal

**Comment by chocolatecupcake2002** [comment]
> @PranavBarthwal

@PranavBarthwal

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Chatbot is good but please restore the original background gradient.

**Comment by chocolatecupcake2002** [comment]
> Chatbot is good but please restore the original background gradient.

Great to know, can you clarify on original background gradient? you would like the previous css i had placed (black..white.. shown in issues) or the same as of webpage?

**Comment by PranavBarthwal** [comment]
> > Chatbot is good but please restore the original background gradient.
> 
> Great to know, can you clarify on original background gradient? you would like the previous css i had placed (black..white.. shown in issues) or the same as of webpage?

nvm, someone had submitted the PR for that, so its fixed now. Just resolve the conflicts and tag me once its done, and it'll be merged.

**Review by PranavBarthwal — APPROVED** [review]

**Comment by chocolatecupcake2002** [comment]
@PranavBarthwal  the conflict is resolved pls check

**Review by PranavBarthwal — APPROVED** [review]

**Comment by chocolatecupcake2002** [comment]
@PranavBarthwal can i know when the score will be added for closing this issue and how much is allocated for this task? also requesting to add in contributors list :) thanks.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal can i know when the score will be added for closing this issue and how much is allocated for this task? also requesting to add in contributors list :) thanks.

Next time the leaderboard is updated, you'll be able to see your score in the leaderboard. You'll get 40 or 45 points as this was level 3 issue.

**Pull request merged**
