### PR TITLE
fixed font style #25 (Update Font Style and Color in Accordance with Website Theme)

### PR DESCRIPTION
**Pull request by dhruv389**
# Update Font Style and Color in Accordance with Website Them

## Issue number 

Issue No. : #25

## Video/Screenshots (mandatory)

Screenshot 2024-05-11 214707

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
This PR has merge conflcits.

**Comment by dhruv389** [comment]
can you try again , i made some changes . 
and if it will happen again then please guide me what i have to do?

**Review by dhruv389 — COMMENTED** [review]
fixed all conflicts. please merge this pull request.

**Comment by dhruv389** [comment]
Please merge this pull request and close issue no: #25

**Pull request closed without merging**
