### PR TITLE
fix: Add Particles background 

### PR DESCRIPTION
**Pull request by DonaldReddy**
# Add Particles background 

## Issue number 
fixes: #270 

## Video/Screenshots (mandatory)

[29_5_2024, 1_15_57 am - Screen - Untitled video.webm](https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/a581bef2-39c8-42c9-aed8-586e22a7e79f)

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Can you use the one used here : https://www.namespacecomm.in/
https://github.com/namespacecomm/NSCC-BPIT-Website

**Comment by DonaldReddy** [comment]
@PranavBarthwal it is implemented in three js, I can do it.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal it is implemented in three js, I can do it.

Go ahead 🚀

**Comment by DonaldReddy** [comment]
Hey @PranavBarthwal , i have used React Three Fiber to create this 3D star field.
https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/c148ffef-90a2-4b1a-981e-6bc7d3f6f539

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
