### PR TITLE
Add Loader Animation to Mars Rover Display Section during API call

### LINKED ISSUE #117: Add Loader Animation to Mars Rover Display Section during API call
### Describe the feature

Adding Loader animation to Mars Rover Display section during API call which matches the website theme.

this is the loader I would like to add 👇

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/000f5077-61a8-4d96-85a1-69abc6a997e6

### It should be implemented because

Adding Loader animation during API calls improves the user experience.

### Additional context

I can also add this loader to the APoD section.

Please assign this issue to me @PranavBarthwal 

### Would you like to work on this issue?

Yes

### PR DESCRIPTION
**Pull request by DonaldReddy**
Fixes #117 

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/51c57da3-6ab2-4243-ad99-d1fcf4c84955

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

I've added loading animation to APoD and Rover Section.

### CODE REVIEW

**Comment by DonaldReddy** [comment]
Hey @PranavBarthwal should we wait till project migration happens?

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
PR has merge conflicts please resolve them

**Comment by DonaldReddy** [comment]
@PranavBarthwal some previous merges have changed the UI and navbar links to other pages, please look into it.

**Comment by DonaldReddy** [comment]
@surajvast1 some previous merges have changed the UI and navbar links to other pages,
Someone has opened the pull request without syncing with the latest merge. please look into it.

**Comment by surajvast1** [comment]
The project is currently in very initial stage and some important issues are yet to be completed. Lets keep this on hold currently.
We will get back to you ||

**Pull request closed without merging**
