### PR TITLE
[Doc]: Improving main Readme/md file

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #317

# Title of Issue and Pull Request must be Same

## Issue number 

Issue No. :  #317 

## Video/Screenshots (mandatory)

image

image

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:

Added code

```
![GitHub issues](https://img.shields.io/github/issues/PranavBarthwal/cosmoXplore) <br>
![GitHub forks](https://img.shields.io/github/forks/PranavBarthwal/cosmoXplore) <br>
![GitHub pull requests](https://img.shields.io/github/issues-pr/PranavBarthwal/cosmoXplore) <br>
![GitHub Repo stars](https://img.shields.io/github/stars/PranavBarthwal/cosmoXplore?style=social) <br>
![GitHub contributors](https://img.shields.io/github/contributors/PranavBarthwal/cosmoXplore) <br>
---


<h2><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/High%20Voltage.png" alt="High Voltage" width="40" height="40" /><font size="6">Tech Stack</font></h2>

<a href="https://developer.mozilla.org/en-US/docs/Glossary/HTML5"><img src="https://img.shields.io/badge/HTML5-E34F26.svg?style=for-the-badge&logo=HTML5&logoColor=white"></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"><img src="https://img.shields.io/badge/JavaScript-F7DF1E.svg?style=for-the-badge&logo=JavaScript&logoColor=black"></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS"><img src="https://img.shields.io/badge/CSS3-1572B6.svg?style=for-the-badge&logo=CSS3&logoColor=black"></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/React"><img src="https://img.shields.io/badge/React-1572B6.svg?style=for-the-badge&logo=React&logoColor=black"></a>

---
## <img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Rocket.png" alt="Rocket" width="40" height="40" /> Steps to Run the Project 👨‍💻

<div align="center">
<h2><font size="6"><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Red%20Heart.png" alt="Red Heart" width="40" height="40" /> Contributors </font></h2>
</div>
<br>

- This project thanking all the contributors for having your valuable contribution to our project
- Make sure you show some love by giving ⭐ to our repository

<br>

<center>
<a href="https://github.com/PranavBarthwal/cosmoXplore/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=PranavBarthwal/cosmoXplore" />
</a>
</center>
<br>
<p align="right"><a href="#top">Back to top</a></p>
```

### CODE REVIEW

**Review by PranavBarthwal — APPROVED** [review]

**Comment by Anjaliavv51** [comment]
@PranavBarthwal please add level Labels

**Comment by Anjaliavv51** [comment]
@PranavBarthwal @surajvast1 please add level Labels  to PR

**Comment by PranavBarthwal** [comment]
We have been instructed by the program managers to not assign any level to documentation changes :)

**Comment by Anjaliavv51** [comment]
Okay

**Pull request merged**
