### PR TITLE
Making navbar responsive for all devices 

### PR DESCRIPTION
**Pull request by saketh-05**
# Title of Issue and Pull Request must be Same

## Issue number 

Issue No. : #276  

closes : #276 

## Video/Screenshots (mandatory)

Screenshot 2024-06-02 200448
Screenshot 2024-06-02 201608
Screenshot 2024-06-02 201625

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by saketh-05** [comment]
@PranavBarthwal Resolved all conflicts. Please review my PR.

**Comment by saketh-05** [comment]
@PranavBarthwal Please review my pr and tell me if any changes are to be done.

**Comment by PranavBarthwal** [comment]
issue already resolved

**Pull request closed without merging**
