### PR TITLE
Automatic addition od GSSOC , Bug , Enchancement and Documnetation label

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#465

# Title of Issue and Pull Request must be Same

## Issue number 

#465 

closes: #465 

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@PranavBarthwal make sure to "Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions" after merging of the PR.

**Comment by Anjaliavv51** [comment]
@PranavBarthwal @surajvast1 please review the PR

**Comment by Anjaliavv51** [comment]
@PranavBarthwal @surajvast1 please review the PR

@PranavBarthwal make sure to "Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions" after merging of the PR.

**Comment by Anjaliavv51** [comment]
@PranavBarthwal please review the PR

**Comment by Anjaliavv51** [comment]
@PranavBarthwal @surajvast1 please review the PR

@PranavBarthwal make sure to "Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions" after merging of the PR.

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
