### PR TITLE
Would like to add preloader?

### PR DESCRIPTION
**Pull request by Anjaliavv51**
# Related Issue
Issue #91 

##Before Changes:

https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/9d3c7d4f-72c0-4a1f-9f08-9912a7e13b94

## After Changes :
https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/4e229379-f315-40c6-a5f0-e09e1a4d9258

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:
**Code Changes**

`<div class="l">`
    `<div class="spinner">`
    `</div>`
`</div>`
    `<script>`
     ` window.addEventListener("load", () => {`
`  const loader = document.querySelector(".l");`
 ` loader.classList.add("l--hidden");` 
`  loader.addEventListener("transitionend", () => {`
 ` document.body.removeChild(loader);`
 ` });`
 ` });`
     ` window.addEventListener("load", () => {`
  `const loader = document.querySelector(".spinner");`
  `loader.classList.add("spinner--hidden");`
 ` loader.addEventListener("transitionend", () => {`
  `document.body.removeChild(loader);`
  `});`
 ` });`
    `</script>`

.spinner {
  background-image: linear-gradient(rgb(186, 66, 255) 35%,rgb(0, 225, 255));
  width: 100px;
  height: 100px;
  animation: spinning82341 1.7s linear infinite;
  transition: opacity 3s,visibility 3s;
  text-align: center;
  border-radius: 50px;
  filter: blur(1px);
  box-shadow: 0px -5px 20px 0px rgb(186, 66, 255), 0px 5px 20px 0px rgb(0, 225, 255);
}
.spinner--hidden{
    opacity: 0;
    visibility: hidden;
}
@keyframes spinning82341 {
  to {
    transform: rotate(360deg);
  }
}
.l{
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: black;
  transition: opacity 3s, visibility 3s;
  z-index: 100;
}

.l--hidden {
  opacity: 0;
  visibility: hidden;
}

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
**Please review the commits and change it**

**Comment by Anjaliavv51** [comment]
**Merge**
Commits withe name Update style.css & index.html

**Comment by Anjaliavv51** [comment]
**Merge**
Commits withe name Update style.css & Update index.html

**Review by Anjaliavv51 — COMMENTED** [review]
Changes Done!!

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Can you please hide the navbar while the loader is showing.
Screenshot (207)

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
Please check now ,I had edited the code.

**Comment by Anjaliavv51** [comment]
Add extra code to style.css file:
.navbar{
  z-index: 99;
}

After changes:

https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/af7a88b7-d8b0-460f-b28a-0f6dc6b9d925

The navigation bar is hidden while the preloader is active.

**Pull request closed without merging**
