### PR TITLE
Enhancement in home page 

### PR DESCRIPTION
**Pull request by Chandu6702**
closes: #229 

## Video/Screenshots (mandatory)

https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/23784c66-e6e0-4146-8217-cefd0a69275f

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:
I have enhanced the UI in home page by adding proper margins,padding and also enhanced the animation of the images.

### CODE REVIEW

**Comment by Chandu6702** [comment]
@surajvast1 and @PranavBarthwal  please review and merge this PR

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Still not resolved

**Comment by surajvast1** [comment]
@Chandu6702 I don't seee the enhancements .Could you justify what have you changed in detail

**Comment by surajvast1** [comment]
Okkk lgtm @PranavBarthwal

**Comment by Chandu6702** [comment]
@surajvast1 yes it is ready to be merged

**Comment by surajvast1** [comment]
LGTM @PranavBarthwal

**Comment by Chandu6702** [comment]
@PranavBarthwal please review and merge this PR

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
please resolve conflicts

**Comment by Chandu6702** [comment]
@PranavBarthwal  as this PR deals with every section on the home page even a small change in any file creates merge conflicts,
So please merge this before merging other PR

**Pull request closed without merging**
