### PR TITLE
trailing cursor effect 

### PR DESCRIPTION
**Pull request by Chandu6702**
closes: #390 

created a custom cursor and added the trailing effect for the cursor that matches the theme of the website.

## Video/Screenshots (mandatory)

https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/c324a5cc-9b81-4257-9bcd-49379b5c113b

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

### CODE REVIEW

**Comment by Chandu6702** [comment]
@surajvast1 and @PranavBarthwal please review and merge this PR

**Comment by Chandu6702** [comment]
@surajvast1 please review and merge this PR

**Comment by surajvast1** [comment]
I believe its a very big cursor . Do we need this @PranavBarthwal

**Comment by PranavBarthwal** [comment]
> I believe its a very big cursor . Do we need this @PranavBarthwal 

I think the default one is good and minimalistic.

**Comment by Chandu6702** [comment]
@PranavBarthwal ,@surajvast1  I can reduce the size of the custom cursor or should I remove the custom cursor and just add the same trailing effect for the default cursor.

**Comment by surajvast1** [comment]
I don't think its a valid issue you should close this .
Create better issue

**Pull request closed without merging**
