### PR TITLE
Login/Signup Page 

### PR DESCRIPTION
**Pull request by Ojas-Arora**
# Title of Issue and Pull Request must be Same
@PranavBarthwal I have added Login/Signup Page to the website. Kindly review this.

## Issue number 
Fixes issue #411 

closes: #411 
@PranavBarthwal  Kindly review this.

## Video/Screenshots (mandatory)
image

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

### CODE REVIEW

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Kindly review this.

**Comment by Ojas-Arora** [comment]
@surajvast1 @PranavBarthwal  Sir Kindly review this .

**Comment by Ojas-Arora** [comment]
@PranavBarthwal @surajvast1 Sir I have made the pull request almost 2 weeks ago. Kindly review this now . Thanks

**Comment by surajvast1** [comment]
LGTM @PranavBarthwal

**Comment by Ojas-Arora** [comment]
@PranavBarthwal @surajvast1 Please look at this PR as gssoc is about to end in 2 days

**Review by PranavBarthwal — APPROVED** [review]

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Thanks Sir

**Pull request merged**
