### PR TITLE
add favicon to the website

### PR DESCRIPTION
**Pull request by divyalaldinani**
# add favicon to the website

## Issue number 
add favicon to the website #39

Issue No. : 

## Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have gone through the  `contributing.md` file before contributing

## Additional context:
image

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Can you use this image.
favicon

**Comment by divyalaldinani** [comment]
should i remove the background of this or add it as it is..

**Comment by PranavBarthwal** [comment]
> should i remove the background of this or add it as it is..

Please remove it.

**Review by PranavBarthwal — APPROVED** [review]
Good work.

**Pull request merged**
