### PR TITLE
[Doc]: Update Readme to add Environment Variables.

### PR DESCRIPTION
**Pull request by DonaldReddy**
## Issue number 
closes: #300 

## Video/Screenshots (mandatory)
image

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

I've added instructions to add a `.env` file and added `DEMO_KEY` for development purposes.

### CODE REVIEW

**Comment by surajvast1** [comment]
Why is there a need for env??

**Comment by DonaldReddy** [comment]
@surajvast1 An API key is needed to make an API call, And the key is stored and imported from the `.env` file. without it, we can't access the API during the development.

**Comment by surajvast1** [comment]
Yes Correct .
Thanks @DonaldReddy

**Comment by surajvast1** [comment]
LGTM @PranavBarthwal

**Comment by DonaldReddy** [comment]
those are small changes I made to the background animation to improve it.

**Comment by surajvast1** [comment]
Okay LGTM @PranavBarthwal

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
