### PR TITLE
[Feat]: An About Page to Show Founder and Contributors.

### PR DESCRIPTION
**Pull request by DonaldReddy**
# An About Page to Show Founder and Contributors.

## Issue number 
closes: #262 

## Video/Screenshots (mandatory)

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/53a61632-4fe0-4bae-85e0-25d2fb647001

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Good work!
Just resolve the conflicts and then I'll merge.

**Comment by DonaldReddy** [comment]
@PranavBarthwal Please review this PR.

**Comment by DonaldReddy** [comment]
@PranavBarthwal please merge this PR.

**Comment by DonaldReddy** [comment]
@PranavBarthwal this PR should have been merged first. Anyhow please merge it.

**Review by PranavBarthwal — APPROVED** [review]

**Comment by DonaldReddy** [comment]
@PranavBarthwal what is the issue for not merging this PR?

**Review by PranavBarthwal — DISMISSED** [review]

**Review by PranavBarthwal — DISMISSED** [review]

**Comment by PranavBarthwal** [comment]
@DonaldReddy not able to merge even after approving changes, it shows The merge-base changed after approval.

**Comment by DonaldReddy** [comment]
@PranavBarthwal Please try again.

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
