### PR TITLE
Typos in source code

### PR DESCRIPTION
**Pull request by Chandu6702**
fixes : #226 

## Video/Screenshots (mandatory)
Screenshot 2024-05-22 200311
Screenshot 2024-05-22 200145

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:
I have rectified the typos by reviewing all the files and also updated the git ignore file.

### CODE REVIEW

**Comment by Chandu6702** [comment]
@surajvast1 please verify and merge this.

**Comment by Chandu6702** [comment]
@PranavBarthwal I am little confused about labels. the mentor assigned the issue with a level 2 label but you merged the PR
with level1.It may create problem while giving score by gssoc.Please look into it.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal I am little confused about labels. the mentor assigned the issue with a level 2 label but you merged the PR
> with level1.It may create problem while giving score by gssoc.Please look into it.

Updated the label to level2.

**Comment by Chandu6702** [comment]
Thank you

**Pull request merged**
