### PR TITLE
[Bug]:Fix Navbar and Responsiveness

### PR DESCRIPTION
**Pull request by shreyash3087**
This PR fixes the Navbar along with the responsiveness of the website,previously the website had problems with navbar and the responsiveness.The content on smaller screen was overflowing which was reducing the overall user experience for smaller devices.

## Issue number

closes: #335

## Video/Screenshots (mandatory)
**Bug -**

https://github.com/PranavBarthwal/cosmoXplore/assets/72603662/fc39d5ba-d6c3-4b59-a016-a909eeb8c694

**Fix-**

https://github.com/PranavBarthwal/cosmoXplore/assets/72603662/b20b1528-ca77-41c8-b7e4-5627b432d85e

**Screenshots of Fixed Responsiveness-**

**Iphone SE-**

screencapture-localhost-5174-2024-06-05-19_32_29

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@surajvast1 kindly verify the changes,also has any recent commits done by maintaners made some changes to the background color of this website,the light purple background color isnt there on currently deployed website,but if you fork this repo and run it locally there is light purple background.

**Comment by surajvast1** [comment]
We saw this issue .It will be fixed by today and you may pull the changes and modify your images up here

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
good work, just resolve the conflicts

**Comment by shreyash3087** [comment]
@PranavBarthwal it should be good now,can you verify.

thankyou

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
