### PR TITLE
[Feat]: Redesign Mars rover imagery page 

### PR DESCRIPTION
**Pull request by DonaldReddy**
# Redesign Mars rover imagery page

## Issue number 

closes: #343 

## Video/Screenshots (mandatory)

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/eb826fb1-e6b2-4498-be1a-ed77cfd2a240

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

### CODE REVIEW

**Comment by DonaldReddy** [comment]
@PranavBarthwal Please review this PR.

**Comment by DonaldReddy** [comment]
@PranavBarthwal review this PR.

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
The deployment is giving error

image

**Comment by DonaldReddy** [comment]
@PranavBarthwal try now.

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Still giving error

image

**Comment by DonaldReddy** [comment]
@PranavBarthwal i tried deploying this branch on vercel, and everything was fine.
https://cosmo-xplore-phi.vercel.app/

**Comment by surajvast1** [comment]
@DonaldReddy Good job here .But could you align the image and text in some other format. Like image to left and text to right .It looks fine in the mobile view .
You can create a new issue for this

**Comment by surajvast1** [comment]
And also add links and a button for people ho wants to read more about the specific rovers .

**Comment by DonaldReddy** [comment]
Sure @surajvast1, I'll work on that.

**Pull request merged**
