### PR TITLE
fix: Removing Direct DOM Manipulations

### PR DESCRIPTION
**Pull request by DonaldReddy**
# Removing Direct DOM Manipulations

## Issue number 
fixes: #236 

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:

Completly removed DOM manipulation and used react hooks.

### CODE REVIEW

**Comment by DonaldReddy** [comment]
@PranavBarthwal please review this PR.

**Review by PranavBarthwal — APPROVED** [review]
Good work

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Please use API key as an environment variable.

**Comment by DonaldReddy** [comment]
Ok @PranavBarthwal

**Review by PranavBarthwal — APPROVED** [review]

**Comment by DonaldReddy** [comment]
@PranavBarthwal i think you forgot ro add api key in environment variables.
image

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal i think you forgot ro add api key in environment variables.
> image
> 

Yeah, I'll update it on vercel after some time.

**Pull request merged**
