### PR TITLE
Sticky NavBar

### PR DESCRIPTION
**Pull request by ghost**
# Title of Issue and Pull Request must be Same

## Issue number 

Issue No. : #12 

## Video/Screenshots (mandatory)

Screenshot 2024-05-11 at 9 40 28 AM

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

## Additional context:
N/A

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Hi @girish-07 your PR has merge conflicts, please keep your fork up to date by syncing and pulling the changes regularly.
Also, please use `background-image: linear-gradient(to left, rgb(10, 0, 73) , rgb(0, 0, 0));` in navbar style.

**Comment by girish-07** [comment]
Hi @PranavBarthwal , I have resolved the merge conflicts, let me know if I should add the background-image as inline CSS? I prefer having it as a sperate class, let me know if you wish to change that to inline CSS. Thanks.

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Still has conflicts.
please add that styling in the styles.css file, not inline.

**Comment by girish-07** [comment]
@PranavBarthwal  I have merged main with my feature branch could you please take a look

**Review by PranavBarthwal — APPROVED** [review]
Good work.

**Pull request merged**
