### PR TITLE
feat: Enhancing Nav Bar

### PR DESCRIPTION
**Pull request by thecloudcode**
# Enhancing Nav Bar
This PR adds the glass effect to the navbar and improves the css by updating the `Navbar.jsx` and `Navbar.css` files.

## Issue number 
closes: #298 

## Video/Screenshots (mandatory)
**After my changes :**

https://github.com/PranavBarthwal/cosmoXplore/assets/114615639/a85b3966-900f-4107-8eb7-428632ffebbc

Screenshot 2024-06-09 094432

**Before**
image

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:
N/A

### CODE REVIEW

**Comment by surajvast1** [comment]
LGTM @PranavBarthwal

**Review by PranavBarthwal — APPROVED** [review]

**Comment by surajvast1** [comment]
Because of this merge we have lost our responsiveness of the navbar .It was my mistake to approve this.I take full responsibility 
Reverting changes create a new pr @thecloudcode

**Comment by surajvast1** [comment]
@PranavBarthwal Revert this

**Comment by surajvast1** [comment]
merge changes by @DonaldReddy .he created the pr first 
here 
https://github.com/PranavBarthwal/cosmoXplore/issues/388

**Pull request merged**
