### PR TITLE
Issue with input date in mars illustration section

### PR DESCRIPTION
**Pull request by Chandu6702**
fixes : #238 

## Video/Screenshots (mandatory)
Screenshot 2024-05-25 140515

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

## Additional context:
I have updated the functionality and UI of date input .

### CODE REVIEW

**Comment by Chandu6702** [comment]
@surajvast1 please verify and merge this PR.

**Comment by PranavBarthwal** [comment]
> @surajvast1 and @PranavBarthwal please verify and merge this PR.

Please resolve merge conflicts

**Review by PranavBarthwal — APPROVED** [review]

**Comment by Chandu6702** [comment]
@PranavBarthwal please add gssoc label and level2 label .

**Comment by Chandu6702** [comment]
@PranavBarthwal  and @surajvast1  please add label to the PR

**Comment by Chandu6702** [comment]
@PranavBarthwal please add the label

**Pull request merged**
