### PR TITLE
MultiLanguage Facility

### PR DESCRIPTION
**Pull request by Ojas-Arora**
# Title of Issue and Pull Request must be Same
@PranavBarthwal @surajvast1 I have added MultiLanguage Facility to website. Kindly review this.
## Issue number 

closes: #443 

## Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

### CODE REVIEW

**Comment by Ojas-Arora** [comment]
@PranavBarthwal @surajvast1 Kindly please merge the PR as soon as possible as Gssoc is about to end in few days.

**Comment by Ojas-Arora** [comment]
@PranavBarthwal @surajvast1 Kindly please merge the PR till tomorrow as after that will be the last day

**Comment by Ojas-Arora** [comment]
@PranavBarthwal @surajvast1 Sir event is about to end kindly do so

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal @surajvast1 Sir please its a request

Reviewing brother.

**Comment by Ojas-Arora** [comment]
Thanks sir

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Can you style that dropdown button according to website's theme and place it in navbar next to contact us.

Rest is fine, once this is done do tag me, I'll merge.
Good work!

**Comment by Ojas-Arora** [comment]
@PranavBarthwal ok

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Done

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Kindly review this

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Kindly see the latest one

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
Please fix this, and improve its style

image

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Ok sir i will fix this and sir style of the multilanguage option cant be changes it is made just like this

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal Ok sir i will fix this and sir style of the multilanguage option cant be changes it is made just like this

I see. So just add this in the footer
Below copyright statement.
In the center.

**Comment by Ojas-Arora** [comment]
@PranavBarthwal ok

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Done sir kindly review.

**Comment by Ojas-Arora** [comment]
@PranavBarthwal Is this ok now?

**Comment by surajvast1** [comment]
LGTM @PranavBarthwal

**Comment by surajvast1** [comment]
Review it and merge this @PranavBarthwal

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
